=== uo295228/LaVuelta2026/xml/etapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" 
           elementFormDefault="qualified" 
           targetNamespace="http://www.uniovi.es" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="numero" />
				<xs:element ref="tipo" />
				<xs:element ref="fecha" />
				<xs:element ref="longitud" />
				<xs:element ref="desnivel" />
				<xs:element ref="ciudad_salida" />
				<xs:element ref="ciudad_llegada" />
				<xs:element ref="tiempo_ganador" />
				<xs:element ref="velocidad_media_ganador" />
				<xs:element ref="referencias" />
				<xs:element ref="galeria_fotografias" />
				<xs:element ref="galeria_videos" />
				<xs:element ref="galeria_sonidos" />
				<xs:element ref="coordenadas_salida" />
				<xs:element ref="coordenadas_llegada" />
				<xs:element ref="hitos" />
				<xs:element ref="puntos_anonimos" />
				<xs:element ref="clasificaciones" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="numero">
		<xs:simpleType>
			<xs:restriction base="xs:positiveInteger">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="21"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="tipo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="llana"/>
				<xs:enumeration value="montaña"/>
				<xs:enumeration value="media montaña"/>
				<xs:enumeration value="contrarreloj individual"/>
				<xs:enumeration value="contrarreloj por equipos"/>
				<xs:enumeration value="ondulada"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="ciudad_salida" type="xs:string" />
	<xs:element name="ciudad_llegada" type="xs:string" />
	<xs:element name="tiempo_ganador">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="([0-9]{2}:)?[0-9]{2}:[0-9]{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType><xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unidad" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent></xs:complexType>
	</xs:element>

	<xs:element name="desnivel">
		<xs:complexType><xs:simpleContent>
			<xs:extension base="xs:integer">
				<xs:attribute name="unidad" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent></xs:complexType>
	</xs:element>

	<xs:element name="velocidad_media_ganador">
		<xs:complexType><xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unidad" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent></xs:complexType>
	</xs:element>
<xs:element name="referencias">
		<xs:complexType><xs:sequence>
			<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
		</xs:sequence></xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:anyURI" />
	<xs:element name="galeria_fotografias">
		<xs:complexType><xs:sequence>
			<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
		</xs:sequence></xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />

	<xs:element name="galeria_videos">
		<xs:complexType><xs:sequence>
			<xs:element minOccurs="1" maxOccurs="3" ref="video" />
		</xs:sequence></xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />

	<xs:element name="galeria_sonidos">
		<xs:complexType><xs:sequence>
			<xs:element minOccurs="1" maxOccurs="3" ref="audio" />
		</xs:sequence></xs:complexType>
	</xs:element>
	<xs:element name="audio" type="xs:string" />
	<xs:element name="coordenadas_salida">
		<xs:complexType><xs:sequence>
			<xs:element ref="longitud_geo" />
			<xs:element ref="latitud_geo" />
			<xs:element ref="altitud" />
		</xs:sequence></xs:complexType>
	</xs:element>

	<xs:element name="coordenadas_llegada">
		<xs:complexType><xs:sequence>
			<xs:element ref="longitud_geo" />
			<xs:element ref="latitud_geo" />
			<xs:element ref="altitud" />
		</xs:sequence></xs:complexType>
	</xs:element>

	<xs:element name="longitud_geo">
		<xs:complexType><xs:simpleContent>
			<xs:extension base="tipoLongitudAngulo">
				<xs:attribute name="unidad" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent></xs:complexType>
	</xs:element>

	<xs:element name="latitud_geo">
		<xs:complexType><xs:simpleContent>
			<xs:extension base="tipoLatitudAngulo">
				<xs:attribute name="unidad" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent></xs:complexType>
	</xs:element>

	<xs:element name="altitud">
		<xs:complexType><xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unidad" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent></xs:complexType>
	</xs:element>

	<xs:simpleType name="tipoLongitudAngulo">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180.0"/>
			<xs:maxInclusive value="180.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipoLatitudAngulo">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90.0"/>
			<xs:maxInclusive value="90.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="hitos">
		<xs:complexType><xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" ref="hito" />
		</xs:sequence></xs:complexType>
	</xs:element>

	<xs:element name="hito">
		<xs:complexType><xs:sequence>
			<xs:element ref="nombre_hito" />
			<xs:element ref="tipo_hito" />
			<xs:element ref="distancia_salida" />
			<xs:element ref="longitud_geo" />
			<xs:element ref="latitud_geo" />
			<xs:element ref="altitud" />
		</xs:sequence></xs:complexType>
	</xs:element>

	<xs:element name="nombre_hito" type="xs:string" />
	<xs:element name="tipo_hito" type="xs:string" />

	<xs:element name="distancia_salida">
		<xs:complexType><xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="unidad" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent></xs:complexType>
	</xs:element>

	<xs:element name="puntos_anonimos">
		<xs:complexType><xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="punto" />
		</xs:sequence></xs:complexType>
	</xs:element>

	<xs:element name="punto">
		<xs:complexType><xs:sequence>
			<xs:element ref="distancia_salida" />
			<xs:element ref="longitud_geo" />
			<xs:element ref="latitud_geo" />
			<xs:element ref="altitud" />
		</xs:sequence></xs:complexType>
	</xs:element>


	<xs:element name="clasificaciones">
		<xs:complexType><xs:sequence>
			<xs:element ref="clasificacion_etapa" />
			<xs:element ref="clasificacion_general" />
			<xs:element ref="clasificacion_equipos" />
		</xs:sequence></xs:complexType>
	</xs:element>

	<xs:element name="clasificacion_etapa">
		<xs:complexType><xs:sequence>
			<xs:element minOccurs="3" maxOccurs="3" ref="clasificado" />
		</xs:sequence></xs:complexType>
	</xs:element>

	<xs:element name="clasificacion_general">
		<xs:complexType><xs:sequence>
			<xs:element minOccurs="3" maxOccurs="3" ref="clasificado" />
		</xs:sequence></xs:complexType>
	</xs:element>

	<xs:element name="clasificacion_equipos">
		<xs:complexType><xs:sequence>
			<xs:element minOccurs="3" maxOccurs="3" ref="clasificado_equipo" />
		</xs:sequence></xs:complexType>
	</xs:element>

	<xs:element name="clasificado">
		<xs:complexType><xs:sequence>
			<xs:element ref="nombre_ciclista" />
			<xs:element ref="tiempo_diferencia" />
		</xs:sequence>
		<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="nombre_ciclista" type="xs:string" />
	
	<xs:element name="tiempo_diferencia">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="(\+)?[0-9]{2}:[0-9]{2}:[0-9]{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="clasificado_equipo">
		<xs:complexType><xs:sequence>
			<xs:element ref="nombre_equipo" />
			<xs:element ref="tiempo_diferencia" />
		</xs:sequence>
		<xs:attribute name="posicion" type="xs:positiveInteger" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="nombre_equipo" type="xs:string" />
</xs:schema>

=== uo295228/LaVuelta2026/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<etapa xmlns="http://www.uniovi.es"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uniovi.es etapa.xsd">
    
    <!-- Datos de la etapa -->
   <nombre>Cartagena - Lorca</nombre>
    <numero>11</numero>
    <tipo>llana</tipo>
    <fecha>2026-09-02</fecha>
    <longitud unidad="km">153.8</longitud>
    <desnivel unidad="m">1351</desnivel>
    <ciudad_salida>Cartagena</ciudad_salida>
    <ciudad_llegada>Lorca</ciudad_llegada>
    <tiempo_ganador>03:30:00</tiempo_ganador>
    <velocidad_media_ganador unidad="km/h">43.9</velocidad_media_ganador>

    <referencias>
        <referencia>https://www.lavuelta.es/</referencia>
        <referencia>https://cartagena.es/</referencia>
        <referencia>https://lorca.es/</referencia>
    </referencias>

    <galeria_fotografias>
        <fotografia>multimedia/salida.jpg</fotografia>
        <fotografia>multimedia/llegada.jpg</fotografia>
    </galeria_fotografias>

    <galeria_videos>
        <video>multimedia/resumenetapa.mp4</video>
    </galeria_videos>

    <galeria_sonidos>
        <audio>multimedia/resumenetapa.mp3</audio>
    </galeria_sonidos>

    <coordenadas_salida>
        <longitud_geo unidad="grados">-0.9769</longitud_geo>
        <latitud_geo unidad="grados">37.5994</latitud_geo>
        <altitud unidad="m">39.0</altitud>
    </coordenadas_salida>

    <coordenadas_llegada>
        <longitud_geo unidad="grados">-1.7045</longitud_geo>
        <latitud_geo unidad="grados">37.6601</latitud_geo>
        <altitud unidad="m">337.0</altitud>
    </coordenadas_llegada>

    <hitos>
        <hito>
            <nombre_hito>Sprint Intermedio Totana</nombre_hito>
            <tipo_hito>Sprint intermedio</tipo_hito>
            <distancia_salida unidad="km">111.9</distancia_salida>
            <longitud_geo unidad="grados">-1.4981</longitud_geo>
            <latitud_geo unidad="grados">37.7706</latitud_geo>
            <altitud unidad="m">225.0</altitud>
        </hito>
        <hito>
            <nombre_hito>Alto de Aledo</nombre_hito>
            <tipo_hito>Puerto de montaña 3ª categoría</tipo_hito>
            <distancia_salida unidad="km">121.8</distancia_salida>
            <longitud_geo unidad="grados">-1.5739</longitud_geo>
            <latitud_geo unidad="grados">37.7944</latitud_geo>
            <altitud unidad="m">623.0</altitud>
        </hito>
    </hitos>

    <puntos_anonimos>
        <punto>
            <distancia_salida unidad="km">48.5</distancia_salida>
            <longitud_geo unidad="grados">-0.9664</longitud_geo>
            <latitud_geo unidad="grados">37.7425</latitud_geo>
            <altitud unidad="m">36.0</altitud>
        </punto>
        <punto>
            <distancia_salida unidad="km">75.9</distancia_salida>
            <longitud_geo unidad="grados">-1.2167</longitud_geo>
            <latitud_geo unidad="grados">37.7333</latitud_geo>
            <altitud unidad="m">128.0</altitud>
        </punto>
    </puntos_anonimos>

    <clasificaciones>
        <clasificacion_etapa>
            <clasificado posicion="1">
                <nombre_ciclista>J. Brennan</nombre_ciclista>
                <tiempo_diferencia>03:17:18</tiempo_diferencia>
            </clasificado>
            <clasificado posicion="2">
                <nombre_ciclista>B. Coquard</nombre_ciclista>
                <tiempo_diferencia>+00:00:00</tiempo_diferencia>
            </clasificado>
            <clasificado posicion="3">
                <nombre_ciclista>J. Meeus</nombre_ciclista>
                <tiempo_diferencia>+00:00:00</tiempo_diferencia>
            </clasificado>
        </clasificacion_etapa>

        <clasificacion_general>
            <clasificado posicion="1">
                <nombre_ciclista>J. Brennan</nombre_ciclista>
                <tiempo_diferencia>+00:00:00</tiempo_diferencia>
            </clasificado>
            <clasificado posicion="2">
                <nombre_ciclista>B. Coquard</nombre_ciclista>
                <tiempo_diferencia>+00:00:00</tiempo_diferencia>
            </clasificado>
            <clasificado posicion="3">
                <nombre_ciclista>J. Meeus</nombre_ciclista>
                <tiempo_diferencia>00:00:00</tiempo_diferencia>
            </clasificado>
        </clasificacion_general>

        <clasificacion_equipos>
            <clasificado_equipo posicion="1">
                <nombre_equipo>XDS Astana Team</nombre_equipo>
                <tiempo_diferencia>09:51:54</tiempo_diferencia>
            </clasificado_equipo>
            <clasificado_equipo posicion="2">
                <nombre_equipo>Groupama-FDJ United</nombre_equipo>
                <tiempo_diferencia>+00:00:00</tiempo_diferencia>
            </clasificado_equipo>
            <clasificado_equipo posicion="3">
                <nombre_equipo>Team Visma | Lease a Bike</nombre_equipo>
                <tiempo_diferencia>+00:00:00</tiempo_diferencia>
            </clasificado_equipo>
        </clasificacion_equipos>
    </clasificaciones>

    
</etapa>
